<?php 

namespace Store\Store\Updates\Seeders;

use Seeder;
use DB ;

class SeedCategoriesTable extends Seeder
{
    public function run()
    {
        DB::table('store_store_categories')->insert([
  [
                'name' => 'فساتين',
                'slug' => 'dresses',
                'color' => '#000000ff',
                'status' => true,
                'is_featured' => true,
                'is_top' => true,
                'show_homepage' => true,
                'is_popular' => true,
                'is_trending' => false,
                'description' => 'أحدث مجموعة الفساتين النسائية بجميع الأنواع والتصاميم',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس علوية',
                'slug' => 'tops',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => true,
                'is_featured' => true,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'تيشيرتات، بلوزات، كروتات وقمصان نسائية',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس سفلية',
                'slug' => 'bottoms',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => true,
                'is_featured' => true,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'بناطيل، جينز، تنانير وشورتات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس خارجية',
                'slug' => 'outerwear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => true,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => true,
                'is_trending' => false,
                'description' => 'معاطف، جاكيتات، وسترات للطقس البارد',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس رياضية',
                'slug' => 'sportswear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => true,
                'description' => 'ملابس التمرين واليوجا والرياضة',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس النوم',
                'slug' => 'sleepwear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'بيجامات، نايتروب، وملابس نوم مريحة',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس داخلية',
                'slug' => 'lingerie',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس داخلية نسائية عصرية وجميلة',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس السباحة',
                'slug' => 'swimwear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => true,
                'description' => 'بيكينيات وملابس سباحة بأحدث الموديلات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'أحذية',
                'slug' => 'shoes',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => true,
                'is_popular' => true,
                'is_trending' => false,
                'description' => 'أحذية بكعب، شبشب، صندل، وأحذية رياضية',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'حقائب',
                'slug' => 'bags',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => true,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'حقائب يد، شنط ظهر، حقائب كتف وأكسسوارات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'إكسسوارات',
                'slug' => 'accessories',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'أساور، عقود، خواتم، وساعات نسائية',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'مجوهرات',
                'slug' => 'jewelry',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => true,
                'is_trending' => false,
                'description' => 'مجوهرات ذهب وفضة ومجوهرات مميزة',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس حفلات',
                'slug' => 'party-wear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => true,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'فساتين سهرة وملابس للحفلات والمناسبات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس زفاف',
                'slug' => 'wedding',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'فساتين زفاف وملابس للعروس والحفلات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس العمل',
                'slug' => 'workwear',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس مكتبية رسمية وأنيقة للعمل',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس الحمل',
                'slug' => 'maternity',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس مريحة وأنيقة للحوامل',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس كاجوال',
                'slug' => 'casual',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => true,
                'is_trending' => false,
                'description' => 'ملابس يومية مريحة وعصرية',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس شتوية',
                'slug' => 'winter',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => true,
                'description' => 'ملابس دافئة ومناسبة لفصل الشتاء',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس صيفية',
                'slug' => 'summer',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => true,
                'description' => 'ملابس خفيفة ومناسبة لفصل الصيف',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس كبيرة الحجم',
                'slug' => 'plus-size',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس مخصصة للنساء صاحبات الحجم الكبير',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس نسائية إسلامية',
                'slug' => 'modest-fashion',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => true,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس محتشمة وأنيقة تناسب النساء المسلمات',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ملابس مستوحاة من التراث',
                'slug' => 'traditional',
                'color' => '#000000ff',
                'status' => true,
                'show_homepage' => false,
                'is_featured' => false,
                'is_top' => false,
                'is_popular' => false,
                'is_trending' => false,
                'description' => 'ملابس تراثية وتقليدية بأسلوب عصري',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}   
